// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQBlH6TFxgm8uAzgaSlvAbALjUDgebAds',
    appId: '1:354769746711:web:68a2ab01708e52f86b1552',
    messagingSenderId: '354769746711',
    projectId: 'bar-ops',
    authDomain: 'bar-ops.firebaseapp.com',
    storageBucket: 'bar-ops.firebasestorage.app',
    measurementId: 'G-TFC9KNT059',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb52tOpHGdP1IfKng0hZ1Jtx9Ohb-QCFc',
    appId: '1:354769746711:android:1c27fa48068b34166b1552',
    messagingSenderId: '354769746711',
    projectId: 'bar-ops',
    storageBucket: 'bar-ops.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZCLYtGSqMkkwCT-ojxL840ThBJUv5fQA',
    appId: '1:354769746711:ios:1f477b8b13d8375e6b1552',
    messagingSenderId: '354769746711',
    projectId: 'bar-ops',
    storageBucket: 'bar-ops.firebasestorage.app',
    iosBundleId: 'com.example.barOps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZCLYtGSqMkkwCT-ojxL840ThBJUv5fQA',
    appId: '1:354769746711:ios:1f477b8b13d8375e6b1552',
    messagingSenderId: '354769746711',
    projectId: 'bar-ops',
    storageBucket: 'bar-ops.firebasestorage.app',
    iosBundleId: 'com.example.barOps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQBlH6TFxgm8uAzgaSlvAbALjUDgebAds',
    appId: '1:354769746711:web:185bd42761e378386b1552',
    messagingSenderId: '354769746711',
    projectId: 'bar-ops',
    authDomain: 'bar-ops.firebaseapp.com',
    storageBucket: 'bar-ops.firebasestorage.app',
    measurementId: 'G-VE2VKBWVR5',
  );

}